### ISSUE TITLE
Optimization? getLogger()

### ISSUE THREAD

**Issue by rbp15** [Civcraft/CivSpy#11]
Would be more optimized to declare getLogger() once and then access that instance?
I see it calling logger multiple times - unless their is a logger queue happening where each instance is added to a stack of log calls that are to be executed?

Such as:
`private static org.apache.log4j.Logger log = Logger.getLogger(LogClass.class);`

?

**Comment by ProgrammerDan** [comment]
Went through and change in Bungee code; most other classes at this point take a reference to a definite JUL logger. Someday I might switch it over to the log4j provider, but for now just using the one that Bukkit provides via JavaPlugin (which is JUL). Thanks!
